# Generated by Django 3.0.1 on 2019-12-25 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='Usertype',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='login',
            name='Password',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='login',
            name='Username',
            field=models.CharField(default='', max_length=50),
        ),
    ]
