# Generated by Django 3.0.1 on 2019-12-29 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_images_image_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pics',
            fields=[
                ('pic_id', models.AutoField(primary_key=True, serialize=False)),
                ('Picture', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.DeleteModel(
            name='Images',
        ),
    ]
