# Generated by Django 4.0.4 on 2022-05-26 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_category_project_expense_category_project'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
