# Generated by Django 3.1 on 2021-06-10 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('post_desc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.post')),
            ],
        ),
    ]
