# Generated by Django 3.1 on 2021-06-13 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_auto_20210613_0752'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pyment',
            new_name='Payment',
        ),
    ]
