# Generated by Django 3.0.3 on 2020-04-25 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdata',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
