# Generated by Django 3.1 on 2021-05-30 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_auto_20210530_0839'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='extra_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
