# Generated by Django 3.1 on 2021-05-30 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_blog_extra_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='tags',
            field=models.CharField(choices=[('TECH', 'TECH'), ('JOES', 'JOES'), ('DJANGO', 'DJANGO'), ('REACT', 'REACT')], default='TECH', max_length=100),
        ),
    ]
