# Generated by Django 3.1 on 2021-06-08 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_auto_20210530_1018'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name_plural': 'Blog'},
        ),
    ]
