# Generated by Django 2.2.12 on 2022-04-16 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_option_question_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='fee',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
