# Generated by Django 2.2.12 on 2022-04-16 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_auto_20220416_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='discount',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
