# Generated by Django 3.1 on 2021-06-24 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='shubham', max_length=20),
            preserve_default=False,
        ),
    ]
