# Generated by Django 3.1 on 2021-06-24 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=20),
        ),
    ]
